In [41]:
import numpy as np


In [42]:
# Q1
array = [5, 9, 2, 1, 8, 4, 6, 12, 3, 10, 7, 11]

array_3d = np.array(array)
array_3d = array_3d.reshape(4,3)
array_3d


array([[ 5,  9,  2],
       [ 1,  8,  4],
       [ 6, 12,  3],
       [10,  7, 11]])

In [43]:
# Q2
multiplied_array = np.dot(array_3d, array_3d.T)
multiplied_array

array([[110,  85, 144, 135],
       [ 85,  81, 114, 110],
       [144, 114, 189, 177],
       [135, 110, 177, 270]])

In [44]:
# Q3
array = np.array([3,5,23,54,32,45,123,12])
print('before split:', array, '\n')
split_array = np.split(array, 2)

print('after split:')
for ele in split_array:
    print(ele)


before split: [  3   5  23  54  32  45 123  12] 

after split:
[ 3  5 23 54]
[ 32  45 123  12]
